#!/bin/bash


for i in `seq 500`; do 
make_random_timing.py -num_stim 3 -num_runs 1 \
-run_time 300 \
-stim_labels A B C \
-num_reps 20 \
-prefix stimt \
-stim_dur 1 \
-seed $i 

3dDeconvolve -nodata 300 1 -polort 1 \
-num_stimts 3 \
-stim_times 1 stimt_01_A.1D 'GAM' -stim_label 1 'A' \
-stim_times 2 stimt_02_B.1D 'GAM' -stim_label 2 'B' \
-stim_times 3 stimt_03_C.1D 'GAM' -stim_label 3 'C' \
-gltsym "SYM: A -B" -gltsym "SYM: A -C" \
>> out2.txt

efficiency=`python efficiency_parser.py out2.txt`
echo $efficiency $i >> efficiencylist2.txt
done


sort -k1 -n efficiencylist2.txt
mv stim*.1D times
mv 3dDeconvolve.err nodata.XtXinv.xmat nodata.xmat.1D  times
mv out1.txt efficiencylist1.txt results

#best design is .1872 1